### PR TITLE
fix(ebs): only delete items if snapshot was actually pruned

### LINKED ISSUE #14: dynamodb entries get deleted after being added

### PR DESCRIPTION
**Pull request by jhedev**
Fixes #14

### CODE REVIEW

File: pkg/snapshot/ec2/ec2.go [hunk 1]
```diff
@@ -338,22 +338,23 @@ func (smgr *SnapshotManager) Prune(ctx context.Context) error {
...
+					ID:       datastore.SnapshotID(*snap.SnapshotId),
+					// The createdAt timestamp is used as a key for ordering
+					// in the datatstore. Hence we need to ensure it is
+					// stable. To avoid problems it was truncated to one
+					// minute during creation above
+					CreatedAt: (*snap.StartTime).Truncate(time.Minute),
+				}); err != nil {
+					smgr.logger.Error(err)
+				}
+				break
```
Comment (philippfranke) [inline pkg/snapshot/ec2/ec2.go:355]: Do you need this break?

**Review by philippfranke — COMMENTED** [review]
❓

File: pkg/snapshot/ec2/ec2.go (hunk 1 above)
Comment (jhedev) [reply pkg/snapshot/ec2/ec2.go:355]: yes

**Review by philippfranke — APPROVED** [review]
